pipeline {
    agent { 
        node {
            label 'docker-agent-python'
        }
    }
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building..."
                sh 'pip install -r jenkins_101/myapp/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                sh 'python3 jenkins_101/myapp/hello.py'
                sh 'python3 jenkins_101/myapp/hello.py --name=Brad'
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivering..."
                sh 'echo "doing delivery stuff..."'
            }
        }
    }
}
