pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out source code..."
                checkout scm
            }
        }

        stage('Test') {
            steps {
                bat '''
                  echo Running basic tests...
                  echo All tests passed!
                '''
            }
        }

        stage('Build') {
            steps {
                bat '''
                  echo Building static app...
                  echo (no build steps needed for HTML/CSS/JS)
                '''
            }
        }

        stage('Deploy') {
            steps {
                bat '''
                  echo Deploy handled by GitHub Pages after push.
                '''
            }
        }
    }
}
